name: Build Clothoids Wrapper

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        shell: pwsh
        run: |
          choco install -y eigen --version=3.4.0
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y ruby --version=3.0.2
          refreshenv
          gem install colorize rubyzip  # Aggiunto rubyzip

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: Configure and Build
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "Visual Studio 17 2022" -A x64 `
            -DPYTHON_EXECUTABLE="$env:pythonLocation\python.exe" `
            -Dpybind11_DIR="$pwd/submodules/pybind11" `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --target ALL_BUILD -- /m:4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: G2lib
          path: |
            build/Release/G2lib.pyd
            build/Release/Clothoids_win_.dll
            build/Release/Clothoids_win_.lib
